# Generated by Django 4.1.13 on 2025-08-14 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homebanner',
            old_name='description',
            new_name='description1',
        ),
        migrations.AddField(
            model_name='homebanner',
            name='description2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
