# Generated by Django 4.1.13 on 2025-08-14 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_rename_description_homebanner_description1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhyChooseUsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('icon', models.ImageField(upload_to='why_choose_us/')),
            ],
            options={
                'verbose_name': 'Why Choose Us Item',
                'verbose_name_plural': 'Why Choose Us Items',
            },
        ),
        migrations.AlterField(
            model_name='homebanner',
            name='description1',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='homebanner',
            name='description2',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
