# Generated by Django 4.1.13 on 2025-08-14 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_whychooseusitem_alter_homebanner_description1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whychooseusitem',
            name='description',
        ),
        migrations.AddField(
            model_name='homebanner',
            name='description3',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
