# Generated by Django 4.1.13 on 2025-08-14 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_alter_homebanner_description3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homebanner',
            name='description3',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
