# Generated by Django 4.1.13 on 2025-08-14 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_alter_homebanner_description3'),
    ]

    operations = [
        migrations.AddField(
            model_name='whychooseusitem',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='why_choose_us/'),
        ),
    ]
