# Generated by Django 4.1.13 on 2025-08-14 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_whychooseusitem_background_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerBg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='banner_bg/')),
            ],
        ),
        migrations.RemoveField(
            model_name='whychooseusitem',
            name='background_image',
        ),
    ]
