# Generated by Django 4.1.13 on 2025-08-14 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_whychooseusfeature'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiddleSectionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='why_choose_us/middle/')),
                ('alt_text', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
