# Generated by Django 4.1.13 on 2025-08-14 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_middlesectionimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homebanner',
            name='description4',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
