# Generated by Django 4.1.13 on 2025-08-14 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='client_reviews/')),
                ('review_text', models.TextField()),
                ('rating', models.PositiveIntegerField(default=5)),
            ],
        ),
    ]
