# Generated by Django 4.1.13 on 2025-08-14 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_clientreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientreview',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='banner_bg/'),
        ),
        migrations.AlterField(
            model_name='clientreview',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=5.0, max_digits=2),
        ),
    ]
