# Generated by Django 4.1.13 on 2025-08-14 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_clientreview_background_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientreview',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='review/'),
        ),
    ]
