# Generated by Django 4.1.13 on 2025-08-15 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_footer_footercontact_footercategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='facebook_image',
            field=models.ImageField(blank=True, null=True, upload_to='facebook_images/'),
        ),
        migrations.AddField(
            model_name='footer',
            name='instagram_image',
            field=models.ImageField(blank=True, null=True, upload_to='instagram_images/'),
        ),
        migrations.AddField(
            model_name='footer',
            name='youtube_image',
            field=models.ImageField(blank=True, null=True, upload_to='youtube_images/'),
        ),
    ]
