# Generated by Django 4.1.13 on 2025-08-15 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_footer_facebook_image_footer_instagram_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footer',
            name='facebook_image',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='instagram_image',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='youtube_image',
        ),
        migrations.AddField(
            model_name='footer',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='footer_images/'),
        ),
    ]
