# Generated by Django 4.1.13 on 2025-08-15 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0019_remove_footer_icon_footer_facebook_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientreview',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
