# Generated by Django 4.1.13 on 2025-08-15 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0022_aboutsection'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('service_image', models.ImageField(upload_to='about_images/')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Services', max_length=100)),
                ('highlight', models.CharField(default='Nagercoil Builders', max_length=100)),
                ('description', models.TextField()),
            ],
        ),
    ]
