# Generated by Django 4.1.13 on 2025-08-15 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0023_servicebanner_servicesection'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServiceSection',
        ),
        migrations.AlterField(
            model_name='servicebanner',
            name='service_image',
            field=models.ImageField(upload_to='service_images/'),
        ),
    ]
