# Generated by Django 4.1.13 on 2025-08-16 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0025_servicesection'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('project_image', models.ImageField(upload_to='service_images/')),
            ],
        ),
    ]
