# Generated by Django 4.1.13 on 2025-08-16 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0026_projectbanner'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='projects/')),
            ],
        ),
        migrations.AlterField(
            model_name='projectbanner',
            name='project_image',
            field=models.ImageField(upload_to='project_images/'),
        ),
    ]
