# Generated by Django 4.1.13 on 2025-08-16 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0027_projectsection_alter_projectbanner_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsection',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='projects/'),
        ),
    ]
