# Generated by Django 4.1.13 on 2025-08-16 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0028_projectsection_image1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectsection',
            name='image1',
        ),
        migrations.AddField(
            model_name='servicesection',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='services/'),
        ),
    ]
