# Generated by Django 4.1.13 on 2025-08-16 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0029_remove_projectsection_image1_servicesection_image1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicebanner',
            name='service_image',
        ),
        migrations.RemoveField(
            model_name='servicesection',
            name='image1',
        ),
        migrations.CreateModel(
            name='ServiceBannerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='service_images/')),
                ('description', models.TextField(blank=True)),
                ('banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='mainapp.servicebanner')),
            ],
        ),
    ]
