# Generated by Django 4.1.13 on 2025-08-16 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0030_remove_servicebanner_service_image_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServiceBannerImage',
        ),
    ]
