# Generated by Django 4.1.13 on 2025-08-16 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0031_delete_servicebannerimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicebanner',
            name='service_image',
            field=models.ImageField(blank=True, null=True, upload_to='service_images/'),
        ),
    ]
