# Generated by Django 4.1.13 on 2025-08-16 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0033_remove_servicebanner_service_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicebanner',
            name='title1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
