# Generated by Django 4.1.13 on 2025-08-16 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0034_servicebanner_title1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicebanner',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
