# Generated by Django 4.1.13 on 2025-08-16 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0035_alter_servicebanner_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicebannerimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='services/'),
        ),
        migrations.AlterField(
            model_name='servicesection',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='services/'),
        ),
    ]
