# Generated by Django 4.1.13 on 2025-08-16 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0036_alter_servicebannerimage_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicebannerimage',
            name='servicesection_image',
            field=models.ImageField(blank=True, null=True, upload_to='services/'),
        ),
        migrations.AlterField(
            model_name='servicebannerimage',
            name='image',
            field=models.ImageField(upload_to='service_images/, blank=True, null=True'),
        ),
    ]
