# Generated by Django 4.1.13 on 2025-08-16 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0037_servicebannerimage_servicesection_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicebannerimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='service_images/'),
        ),
    ]
