# Generated by Django 4.1.13 on 2025-08-16 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0038_alter_servicebannerimage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_banner_heading', models.CharField(blank=True, max_length=255, null=True)),
                ('first_banner_description', models.TextField(blank=True, null=True)),
                ('second_banner_heading', models.CharField(blank=True, max_length=255, null=True)),
                ('second_banner_description', models.TextField(blank=True, null=True)),
                ('second_banner_image', models.ImageField(blank=True, null=True, upload_to='banners/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
            },
        ),
    ]
