# Generated by Django 4.1.13 on 2025-08-16 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0040_secondbannerslide'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirstBannerSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='first_banner/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of display in the carousel')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
