# Generated by Django 4.1.13 on 2025-08-16 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0041_firstbannerslide'),
    ]

    operations = [
        migrations.AddField(
            model_name='secondbannerslide',
            name='second_image',
            field=models.ImageField(blank=True, null=True, upload_to='second_banner/'),
        ),
    ]
