# Generated by Django 4.1.13 on 2025-08-17 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0043_thirdbannerslide'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('contact_image', models.ImageField(upload_to='contact_images/')),
            ],
        ),
        migrations.CreateModel(
            name='ContactSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Contact Us', max_length=100)),
                ('highlight', models.CharField(default='Nagercoil Builders', max_length=100)),
                ('description', models.TextField()),
                ('image1', models.ImageField(upload_to='contact/')),
                ('image2', models.ImageField(upload_to='contact/')),
                ('image3', models.ImageField(upload_to='contact/')),
            ],
        ),
    ]
