# Generated by Django 4.1.13 on 2025-08-17 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0044_contactbanner_contactsection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactsection',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='contactsection',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='contactsection',
            name='image3',
        ),
    ]
