# Generated by Django 4.1.13 on 2025-08-18 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0046_enquiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutbanner',
            name='title',
            field=models.CharField(default='About Us', max_length=200),
        ),
    ]
