# Generated by Django 4.1.13 on 2025-08-18 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0048_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='title',
            field=models.CharField(blank=True, default='FAQ', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='title1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
