# Generated by Django 4.1.13 on 2025-08-18 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0049_faq_title_faq_title1'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='title',
            field=models.CharField(default='Enquiry', max_length=100),
        ),
    ]
