# Generated by Django 4.1.13 on 2025-08-18 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0051_enquirytitle_remove_enquiry_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquirytitle',
            name='description',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='enquirytitle',
            name='enquiry_image',
            field=models.ImageField(blank=True, null=True, upload_to='enquiry_images/'),
        ),
        migrations.AddField(
            model_name='enquirytitle',
            name='title1',
            field=models.CharField(blank=True, default='Enquiry', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='enquirytitle',
            name='title',
            field=models.CharField(blank=True, default='Enquiry', max_length=200, null=True),
        ),
    ]
