# Generated by Django 4.1.13 on 2025-08-18 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0052_enquirytitle_description_enquirytitle_enquiry_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquirytitle',
            name='title2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='enquirytitle',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='enquirytitle',
            name='title1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
