# Generated by Django 4.1.13 on 2025-08-18 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0054_enquiry1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Enquiry1',
        ),
    ]
