# Generated by Django 4.1.13 on 2025-08-18 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0055_delete_enquiry1'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='title2',
            field=models.CharField(blank=True, default='FAQ', max_length=200, null=True),
        ),
    ]
