# Generated by Django 4.1.13 on 2025-08-18 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0056_faq_title2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='title2',
        ),
        migrations.AddField(
            model_name='faq',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
