# Generated by Django 4.1.13 on 2025-08-18 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0057_remove_faq_title2_faq_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('basic', 'Basic'), ('standard', 'Standard'), ('premium', 'Premium')], max_length=50, unique=True)),
                ('price_per_sqft', models.PositiveIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='contactsection',
            name='highlight',
        ),
        migrations.CreateModel(
            name='PackageDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('construction', 'Constructions'), ('electrical', 'Electrical Work'), ('plumbing', 'Plumbing & Painting'), ('extra', 'Extra Work')], max_length=50)),
                ('description', models.TextField()),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='mainapp.package')),
            ],
        ),
    ]
