# Generated by Django 4.1.13 on 2025-08-18 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0058_package_remove_contactsection_highlight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagedetail',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='package_icons/'),
        ),
    ]
