# Generated by Django 4.1.13 on 2025-08-18 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0059_packagedetail_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packagedetail',
            name='description',
        ),
        migrations.RemoveField(
            model_name='packagedetail',
            name='icon',
        ),
        migrations.CreateModel(
            name='PackageItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='package_item_icons/')),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='mainapp.packagedetail')),
            ],
        ),
    ]
