# Generated by Django 4.1.13 on 2025-08-18 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0060_remove_packagedetail_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packageitem',
            name='name',
        ),
        migrations.AddField(
            model_name='packagedetail',
            name='description',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='packagedetail',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='package_icons/'),
        ),
        migrations.AddField(
            model_name='packageitem',
            name='text',
            field=models.CharField(default='', max_length=255),
        ),
    ]
