# Generated by Django 4.1.13 on 2025-08-18 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0061_remove_packageitem_name_packagedetail_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packagedetail',
            name='description',
        ),
        migrations.RemoveField(
            model_name='packagedetail',
            name='icon',
        ),
        migrations.AlterField(
            model_name='package',
            name='name',
            field=models.CharField(choices=[('basic', 'Basic'), ('standard', 'Standard'), ('premium', 'Premium')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='price_per_sqft',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='packagedetail',
            name='category',
            field=models.CharField(choices=[('plan', 'Plan'), ('foundation', 'Foundation'), ('brick', 'Brick'), ('sand', 'Sand'), ('cement', 'Cement'), ('steel', 'Steel'), ('flooring', 'Flooring')], max_length=50),
        ),
    ]
