# Generated by Django 4.1.13 on 2025-08-18 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0062_remove_packagedetail_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packagedetail',
            name='package',
        ),
        migrations.RemoveField(
            model_name='packageitem',
            name='detail',
        ),
        migrations.DeleteModel(
            name='Package',
        ),
        migrations.DeleteModel(
            name='PackageDetail',
        ),
        migrations.DeleteModel(
            name='PackageItem',
        ),
    ]
