# Generated by Django 4.1.13 on 2025-08-18 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0063_remove_packagedetail_package_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsection',
            name='highlight',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
