# Generated by Django 4.1.13 on 2025-08-18 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0065_package_remove_contactsection_highlight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsection',
            name='highlight',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
